services:
  modsec:
    build: .
    container_name: modsec
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./modsec-data/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf
      - ./modsec-data/custom-rules.conf:/etc/nginx/modsec/custom-rules.conf
      - ./modsec-data/crs:/etc/nginx/modsec/crs
      - ./modsec-data/logs/audit.log:/var/log/modsec/audit.log
      - ./modsec-data/logs/error.log:/var/log/nginx/error.log
      - ./modsec-data/logs/access.log:/var/log/nginx/access.log
      - ./modsec-data/nginx.conf:/etc/nginx/nginx.conf
      - ./modsec-data/conf.d:/etc/nginx/conf.d
      - ./modsec-data/html:/var/html
      - ./modsec-data/ssl:/var/ssl
    depends_on:
      - nodeapp
    restart: unless-stopped
  nodeapp:
    build: ./nodeapp
    container_name: nodeapp
    expose:
      - "3000"
